/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface VotingInterface extends Interface {
    getFunction(nameOrSignature: "addProposal" | "chairman" | "changeState" | "commitVote" | "committedCount" | "computeCommitment" | "proposalNames" | "proposals" | "register" | "registeredCount" | "renameProposal" | "results" | "revealVote" | "revealedCount" | "state" | "voterAddresses" | "voters" | "winnerName" | "winningProposal"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Committed" | "Revealed" | "StateChanged" | "VoterRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'addProposal', values: [string]): string;
encodeFunctionData(functionFragment: 'chairman', values?: undefined): string;
encodeFunctionData(functionFragment: 'changeState', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'commitVote', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'committedCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'computeCommitment', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'proposalNames', values?: undefined): string;
encodeFunctionData(functionFragment: 'proposals', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'register', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'registeredCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'renameProposal', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'results', values?: undefined): string;
encodeFunctionData(functionFragment: 'revealVote', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'revealedCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'state', values?: undefined): string;
encodeFunctionData(functionFragment: 'voterAddresses', values?: undefined): string;
encodeFunctionData(functionFragment: 'voters', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'winnerName', values?: undefined): string;
encodeFunctionData(functionFragment: 'winningProposal', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'addProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'chairman', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'changeState', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'commitVote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'committedCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'computeCommitment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposalNames', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'register', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registeredCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renameProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'results', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revealVote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revealedCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'state', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'voterAddresses', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'voters', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'winnerName', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'winningProposal', data: BytesLike): Result;
  }

  
    export namespace CommittedEvent {
      export type InputTuple = [voter: AddressLike, commitment: BytesLike];
      export type OutputTuple = [voter: string, commitment: string];
      export interface OutputObject {voter: string, commitment: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RevealedEvent {
      export type InputTuple = [voter: AddressLike, proposalIndex: BigNumberish];
      export type OutputTuple = [voter: string, proposalIndex: bigint];
      export interface OutputObject {voter: string, proposalIndex: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StateChangedEvent {
      export type InputTuple = [from: BigNumberish, to: BigNumberish];
      export type OutputTuple = [from: bigint, to: bigint];
      export interface OutputObject {from: bigint, to: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoterRegisteredEvent {
      export type InputTuple = [voter: AddressLike];
      export type OutputTuple = [voter: string];
      export interface OutputObject {voter: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Voting extends BaseContract {
    
    connect(runner?: ContractRunner | null): Voting;
    waitForDeployment(): Promise<this>;

    interface: VotingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addProposal: TypedContractMethod<
      [name: string, ],
      [void],
      'nonpayable'
    >
    

    
    chairman: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    changeState: TypedContractMethod<
      [newState: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    commitVote: TypedContractMethod<
      [commitment: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    committedCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    computeCommitment: TypedContractMethod<
      [index: BigNumberish, salt: BytesLike, ],
      [string],
      'view'
    >
    

    
    proposalNames: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    proposals: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint] & {name: string, voteCount: bigint }],
      'view'
    >
    

    
    register: TypedContractMethod<
      [voterAddr: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    registeredCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    renameProposal: TypedContractMethod<
      [idx: BigNumberish, newName: string, ],
      [void],
      'nonpayable'
    >
    

    
    results: TypedContractMethod<
      [],
      [[string[], bigint[]] & {names: string[], votes: bigint[] }],
      'view'
    >
    

    
    revealVote: TypedContractMethod<
      [proposalIndex: BigNumberish, salt: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    revealedCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    state: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    voterAddresses: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    voters: TypedContractMethod<
      [arg0: AddressLike, ],
      [[boolean, boolean, boolean, bigint, string] & {registered: boolean, committed: boolean, revealed: boolean, vote: bigint, commitHash: string }],
      'view'
    >
    

    
    winnerName: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    winningProposal: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addProposal'): TypedContractMethod<
      [name: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'chairman'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'changeState'): TypedContractMethod<
      [newState: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'commitVote'): TypedContractMethod<
      [commitment: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'committedCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'computeCommitment'): TypedContractMethod<
      [index: BigNumberish, salt: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proposalNames'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'proposals'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint] & {name: string, voteCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'register'): TypedContractMethod<
      [voterAddr: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registeredCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renameProposal'): TypedContractMethod<
      [idx: BigNumberish, newName: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'results'): TypedContractMethod<
      [],
      [[string[], bigint[]] & {names: string[], votes: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'revealVote'): TypedContractMethod<
      [proposalIndex: BigNumberish, salt: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revealedCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'state'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'voterAddresses'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'voters'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[boolean, boolean, boolean, bigint, string] & {registered: boolean, committed: boolean, revealed: boolean, vote: bigint, commitHash: string }],
      'view'
    >;
getFunction(nameOrSignature: 'winnerName'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'winningProposal'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'Committed'): TypedContractEvent<CommittedEvent.InputTuple, CommittedEvent.OutputTuple, CommittedEvent.OutputObject>;
getEvent(key: 'Revealed'): TypedContractEvent<RevealedEvent.InputTuple, RevealedEvent.OutputTuple, RevealedEvent.OutputObject>;
getEvent(key: 'StateChanged'): TypedContractEvent<StateChangedEvent.InputTuple, StateChangedEvent.OutputTuple, StateChangedEvent.OutputObject>;
getEvent(key: 'VoterRegistered'): TypedContractEvent<VoterRegisteredEvent.InputTuple, VoterRegisteredEvent.OutputTuple, VoterRegisteredEvent.OutputObject>;

    filters: {
      
      'Committed(address,bytes32)': TypedContractEvent<CommittedEvent.InputTuple, CommittedEvent.OutputTuple, CommittedEvent.OutputObject>;
      Committed: TypedContractEvent<CommittedEvent.InputTuple, CommittedEvent.OutputTuple, CommittedEvent.OutputObject>;
    

      'Revealed(address,uint256)': TypedContractEvent<RevealedEvent.InputTuple, RevealedEvent.OutputTuple, RevealedEvent.OutputObject>;
      Revealed: TypedContractEvent<RevealedEvent.InputTuple, RevealedEvent.OutputTuple, RevealedEvent.OutputObject>;
    

      'StateChanged(uint8,uint8)': TypedContractEvent<StateChangedEvent.InputTuple, StateChangedEvent.OutputTuple, StateChangedEvent.OutputObject>;
      StateChanged: TypedContractEvent<StateChangedEvent.InputTuple, StateChangedEvent.OutputTuple, StateChangedEvent.OutputObject>;
    

      'VoterRegistered(address)': TypedContractEvent<VoterRegisteredEvent.InputTuple, VoterRegisteredEvent.OutputTuple, VoterRegisteredEvent.OutputObject>;
      VoterRegistered: TypedContractEvent<VoterRegisteredEvent.InputTuple, VoterRegisteredEvent.OutputTuple, VoterRegisteredEvent.OutputObject>;
    
    };
  }